<?php
acf_add_local_field_group(array(
	'key' => 'group_603f77d000084',
	'title' => 'School Settings',
	'fields' => array(
		array(
			'key' => 'field_60d9a8ebd47cb',
			'label' => 'NOTICE:',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Saving this page will generate a new stylesheet. This may take a few mintues so please only click on update once.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_603f78be72951',
			'label' => 'School ID',
			'name' => 'school_id',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'svc' => 'svc',
				'nhs' => 'nhs',
				'bcps' => 'bcps',
				'fdcps' => 'fdcps',
				'hcps' => 'hcps',
				'scps' => 'scps',
				'lhjs' => 'lhjs',
				'mpa' => 'mpa',
				'jfa' => 'jfa',
				'bvc' => 'bvc',
				'lvc' => 'lvc',
				'oak' => 'oakes',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_60ae5ecb5a98f',
			'label' => 'School Name',
			'name' => 'school_name',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Sawston Village College' => 'Sawston Village College',
				'The Netherhall School' => 'The Netherhall School',
				'Bottisham Community Primary School' => 'Bottisham Community Primary School',
				'Fen Ditton Community Primary School' => 'Fen Ditton Community Primary School',
				'Howard Community Primary School' => 'Howard Community Primary School',
				'Stapleford Community Primary School' => 'Stapleford Community Primary School',
				'Linton Heights Junior School' => 'Linton Heights Junior School',
				'Marleigh Primary Academy' => 'Marleigh Primary Academy',
				'Joyce Frankland Academy' => 'Joyce Frankland Academy',
				'Bottisham Village College' => 'Bottisham Village College',
				'Linton Village College' => 'Linton Village College',
				'Oakes College' => 'Oakes College',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_609a4fb3e2a03',
			'label' => 'Activate Adult Learning?',
			'name' => 'activate_adult_learning',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Activate' => 'Activate',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_60f80d0efb949',
			'label' => 'Activate Sport Centre?',
			'name' => 'activate_sport_centre',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Activate' => 'Activate',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_603f788773bca',
			'label' => 'School Identity',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6076cb846dccd',
			'label' => 'Laurel',
			'name' => 'laurel',
			'type' => 'true_false',
			'instructions' => 'Would you like the Laurel background to display on the home page?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'message' => 'Yes',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_6130d1bc6fc3e',
			'label' => 'Header Title Location',
			'name' => 'header_title_location',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'center' => 'Center',
				'bottomleft' => 'Bottom Left',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6053599446af4',
			'label' => 'Logo and Icons',
			'name' => 'logo_and_icons',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_605359d146af5',
					'label' => 'School Logo',
					'name' => 'logo',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_60535a0246af6',
					'label' => 'School Icon',
					'name' => 'icon',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_60d1ffa924565',
					'label' => 'Default header image',
					'name' => 'default_header_image',
					'type' => 'image',
					'instructions' => 'For use when a header/featured image is not set on a page',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array(
			'key' => 'field_60535b13e6003',
			'label' => 'Colours',
			'name' => 'colours',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_60535b36e6004',
					'label' => 'Primary Colour',
					'name' => 'primary_colour',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => false,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_60535b53e6005',
					'label' => 'Second Colour',
					'name' => 'second_colour',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => false,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_60537746da74b',
					'label' => 'Image Border Colour',
					'name' => 'border_colour',
					'type' => 'color_picker',
					'instructions' => 'This controls the colour of the line under images',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => false,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_60f98e397d34b',
					'label' => 'Header Social Icon Colour',
					'name' => 'header_social_icon_colour',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'$secondarycolour' => 'Secondary',
						'#FFFFFF' => 'White',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_60785feba43bb',
					'label' => 'Footer Title Colour',
					'name' => 'footer_title_colour',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'$primarycolour' => 'Primary',
						'$secondarycolour' => 'Secondary',
						'#FFFFFF' => 'White',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_607860f5f45e9',
					'label' => 'Footer Icon Colour',
					'name' => 'footer_icon_colour',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'$primarycolour' => 'Primary',
						'$secondarycolour' => 'Secondary',
						'#FFFFFF' => 'White',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_60535bc2f868f',
			'label' => 'Fonts',
			'name' => 'fonts',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_60535bd5f8690',
					'label' => 'Heading Font',
					'name' => 'heading_font',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'\'Raleway\', sans-serif' => 'Raleway',
						'\'Open Sans\', sans-serif' => 'Open Sans',
						'\'Roboto\', sans-serif' => 'Roboto',
						'\'Roboto Slab\', sans-serif' => 'Roboto Slab',
						'\'Josefin Sans\', sans-serif' => 'Josefin Sans',
						'\'Lato\', sans-serif' => 'Lato',
						'\'Libre Franklin \', sans-serif' => 'Libre Franklin',
						'\'Montserrat \', sans-serif' => 'Montserrat',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 1,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_605b1c2c5ef5b',
					'label' => 'Heading Font weight',
					'name' => 'heading_font_weight',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						300 => 'light-weight',
						400 => 'normal-weight',
						600 => 'bold-weight',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_60535c52f8691',
					'label' => 'Body Font',
					'name' => 'body_font',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'\'Raleway\', sans-serif' => 'Raleway',
						'\'Open Sans\', sans-serif' => 'Open Sans',
						'\'Roboto\', sans-serif' => 'Roboto',
						'\'Josefin Sans\', sans-serif' => 'Josefin Sans',
						'\'Lato\', sans-serif' => 'Lato',
						'\'Libre Franklin \', sans-serif' => 'Libre Franklin',
						'\'Montserrat \', sans-serif' => 'Montserrat',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 1,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_605b22a873a8d',
					'label' => 'Body Font Weight',
					'name' => 'body_font_weight',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						300 => 'light-weight',
						400 => 'normal-weight',
						600 => 'bold-weight',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_60535c81f8692',
					'label' => 'Font Previews',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'message' => '<div class="font_choices">
<h3>Raleway</h3>
<p class="raleway">The quick brown fox jumps over the lazy dog</p>
<h3>Roboto</h3>
<p class="roboto">The quick brown fox jumps over the lazy dog</p>
<h3>Roboto Slab</h3>
<p class="robotoslab">The quick brown fox jumps over the lazy dog</p>
<h3>Rubik</h3>
<p class="rubik">The quick brown fox jumps over the lazy dog</p>
<h3>Josefin Sans</h3>
<p class="josefinsans">The quick brown fox jumps over the lazy dog</p>
<h3>Lato</h3>
<p class="lato">The quick brown fox jumps over the lazy dog</p>
<h3>Libre Franklin</h3>
<p class="librefranklin">The quick brown fox jumps over the lazy dog</p>
<h3>Montserrat</h3>
<p class="montserrat">The quick brown fox jumps over the lazy dog</p>
<h3>Open Sans</h3>
<p class="opensans">The quick brown fox jumps over the lazy dog</p>
</div>',
					'new_lines' => '',
					'esc_html' => 0,
				),
			),
		),
		array(
			'key' => 'field_603faa7b17ef3',
			'label' => 'Contact Information',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_603faaa417ef4',
			'label' => 'Telephone',
			'name' => 'telephone',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_603faabb17ef5',
			'label' => 'Email Address',
			'name' => 'email_address',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_603faac717ef6',
			'label' => 'Address',
			'name' => 'address',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_60eeffca19b8c',
					'label' => 'Address Line 1',
					'name' => 'address_line_1',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60eeffd419b8d',
					'label' => 'Street',
					'name' => 'street',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60eeffe119b8e',
					'label' => 'Town',
					'name' => 'town',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60eeffe719b8f',
					'label' => 'City',
					'name' => 'city',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60eeffee19b90',
					'label' => 'County',
					'name' => 'county',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60eefff919b91',
					'label' => 'Postal Code',
					'name' => 'postal_code',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_603fab1351d49',
			'label' => 'Social Media',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_603fab2b51d4a',
			'label' => 'Platforms',
			'name' => 'platforms',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Social Media Platform',
			'sub_fields' => array(
				array(
					'key' => 'field_603fab3651d4b',
					'label' => 'Platform',
					'name' => 'platform',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'facebook' => 'Facebook',
						'twitter' => 'Twitter',
						'instagram' => 'Instagram',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_603fab7a51d4c',
					'label' => 'Profile URL',
					'name' => 'platform_url',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_603fab8851d4d',
					'label' => 'Username',
					'name' => 'username',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_6093bb8f1ff75',
			'label' => 'Partner Logos',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6050871b07d44',
			'label' => 'Carousel',
			'name' => 'carousel',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_6050872707d45',
					'label' => 'image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_6093bc660433a',
					'label' => 'URL',
					'name' => 'url',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_61b0b2084dab3',
					'label' => 'Class',
					'name' => 'class',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_6047a5d882ea8',
			'label' => 'Footer',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6047aa34d467d',
			'label' => 'Background Colour',
			'name' => 'footer_background_colour',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_6077126169cdf',
			'label' => 'Background Image',
			'name' => 'footer_background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '66',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_604635f80d303',
			'label' => 'Left Footer Title',
			'name' => 'left_footer_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6046361d0d304',
			'label' => 'Middle Footer Title',
			'name' => 'middle_footer_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6046362c0d305',
			'label' => 'Right Footer Title',
			'name' => 'right_footer_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_604642aa5bd9c',
			'label' => 'Footer Left Side Text',
			'name' => 'footer_left_side_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '66',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 370,
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6047abec844bb',
			'label' => 'Instagram / Map',
			'name' => 'instagram_map',
			'type' => 'select',
			'instructions' => 'Would you like to display a map or an Instagram feed',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_603fab2b51d4a',
						'operator' => '!=empty',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Instagram' => 'Instagram',
				'Map' => 'Map',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_606d7996285ba',
			'label' => 'latitude',
			'name' => 'latitude',
			'type' => 'number',
			'instructions' => 'This is for use if Map is selected above, and also the map on the contact page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_606d79b6285bb',
			'label' => 'longitude',
			'name' => 'longitude',
			'type' => 'number',
			'instructions' => 'This is for use if Map is selected above, and also the map on the contact page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_609a4ff9e2a04',
			'label' => 'Adult Learning Options',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_609a4fb3e2a03',
						'operator' => '==',
						'value' => 'Activate',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_60bf72f4bef2a',
			'label' => 'Adult Learning Homepage',
			'name' => 'adult_learning_homepage',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'page',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array(
			'key' => 'field_609a5017e2a05',
			'label' => 'Logo and Icons',
			'name' => 'adultlearning_logo_and_icons',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_609a5017e2a06',
					'label' => 'Adult Learning Logo',
					'name' => 'adult_logo',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_609a5017e2a07',
					'label' => 'Adult Learning Icon',
					'name' => 'adult_icon',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array(
			'key' => 'field_612fa56145e28',
			'label' => 'Footer Background Image',
			'name' => 'adult_footer_background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_609a5030e2a08',
			'label' => 'Colours',
			'name' => 'adult_colours',
			'type' => 'group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_609a5031e2a09',
					'label' => 'Primary Colour',
					'name' => 'primary_colour',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#FFFFFF',
					'enable_opacity' => 0,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_609a5031e2a0a',
					'label' => 'Second Colour',
					'name' => 'second_colour',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#FFFFFF',
					'enable_opacity' => 0,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_609a5031e2a0e',
					'label' => 'Footer Icon Colour',
					'name' => 'footer_icon_colour',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'$adultprimarycolour' => 'Primary',
						'$adultsecondarycolour' => 'Secondary',
						'#FFFFFF' => 'White',
					),
					'default_value' => '#FFFFFF',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_609a5031e2a0c',
					'label' => 'Image Border Colour',
					'name' => 'border_colour',
					'type' => 'color_picker',
					'instructions' => 'This controls the colour of the line under images',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#FFFFFF',
					'enable_opacity' => 0,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_609a5031e2a0d',
					'label' => 'Footer Title Colour',
					'name' => 'footer_title_colour',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'$adultprimarycolour' => 'Primary',
						'$adultsecondarycolour' => 'Secondary',
						'#FFFFFF' => 'White',
					),
					'default_value' => '#FFFFFF',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_612fa4504051d',
					'label' => 'Footer Background Colour',
					'name' => 'footer_background_colour',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 0,
					'return_format' => 'string',
				),
			),
		),
		array(
			'key' => 'field_609a503fe2a0f',
			'label' => 'Fonts',
			'name' => 'adult_fonts',
			'type' => 'group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_609a503fe2a10',
					'label' => 'Heading Font',
					'name' => 'heading_font',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '16.6',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'\'Raleway\', sans-serif' => 'Raleway',
						'\'Open Sans\', sans-serif' => 'Open Sans',
						'\'Roboto\', sans-serif' => 'Roboto',
						'\'Roboto Slab\', sans-serif' => 'Roboto Slab',
						'\'Josefin Sans\', sans-serif' => 'Josefin Sans',
						'\'Lato\', sans-serif' => 'Lato',
						'\'Libre Franklin \', sans-serif' => 'Libre Franklin',
						'\'Montserrat \', sans-serif' => 'Montserrat',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 1,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_609a503fe2a11',
					'label' => 'Heading Font weight',
					'name' => 'heading_font_weight',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '16.6',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						300 => 'light-weight',
						400 => 'normal-weight',
						600 => 'bold-weight',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_609a503fe2a12',
					'label' => 'Body Font',
					'name' => 'body_font',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '16.6',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'\'Raleway\', sans-serif' => 'Raleway',
						'\'Open Sans\', sans-serif' => 'Open Sans',
						'\'Roboto\', sans-serif' => 'Roboto',
						'\'Josefin Sans\', sans-serif' => 'Josefin Sans',
						'\'Lato\', sans-serif' => 'Lato',
						'\'Libre Franklin \', sans-serif' => 'Libre Franklin',
						'\'Montserrat \', sans-serif' => 'Montserrat',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 1,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_609a503fe2a13',
					'label' => 'Body Font Weight',
					'name' => 'body_font_weight',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '16.6',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						300 => 'light-weight',
						400 => 'normal-weight',
						600 => 'bold-weight',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_609a503fe2a14',
					'label' => 'Font Previews',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'message' => '<div class="font_choices">
<h3>Raleway</h3>
<p class="raleway">The quick brown fox jumps over the lazy dog</p>
<h3>Roboto</h3>
<p class="roboto">The quick brown fox jumps over the lazy dog</p>
<h3>Roboto Slab</h3>
<p class="robotoslab">The quick brown fox jumps over the lazy dog</p>
<h3>Rubik</h3>
<p class="rubik">The quick brown fox jumps over the lazy dog</p>
<h3>Josefin Sans</h3>
<p class="josefinsans">The quick brown fox jumps over the lazy dog</p>
<h3>Lato</h3>
<p class="lato">The quick brown fox jumps over the lazy dog</p>
<h3>Libre Franklin</h3>
<p class="librefranklin">The quick brown fox jumps over the lazy dog</p>
<h3>Montserrat</h3>
<p class="montserrat">The quick brown fox jumps over the lazy dog</p>
<h3>Open Sans</h3>
<p class="opensans">The quick brown fox jumps over the lazy dog</p>
</div>',
					'new_lines' => '',
					'esc_html' => 0,
				),
			),
		),
		array(
			'key' => 'field_60bf71822d93f',
			'label' => 'Grey Tabs Menu',
			'name' => 'grey_tabs_menu',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'About Us' => 'About Us',
				'Adult Learning' => 'Adult Learning',
				'Adult Learning (Top Buttons)' => 'Adult Learning (Top Buttons)',
				'Adult Learning Main Nav' => 'Adult Learning Main Nav',
				'Alumni' => 'Alumni',
				'Careers Education, Information, Advice and Guidance' => 'Careers Education, Information, Advice and Guidance',
				'Clubs and Activities' => 'Clubs and Activities',
				'Community' => 'Community',
				'Curriculum' => 'Curriculum',
				'Curriculum Rationale' => 'Curriculum Rationale',
				'Ethos and Values' => 'Ethos and Values',
				'Homework' => 'Homework',
				'Houses' => 'Houses',
				'Information' => 'Information',
				'Join Us' => 'Join Us',
				'Letters Home' => 'Letters Home',
				'Main Menu' => 'Main Menu',
				'Parents' => 'Parents',
				'Picture Gallery' => 'Picture Gallery',
				'Pupils' => 'Pupils',
				'Staff' => 'Staff',
				'Subjects' => 'Subjects',
				'Top Buttons (Top Buttons)' => 'Top Buttons (Top Buttons)',
				'Transition (Year 6 - 7)' => 'Transition (Year 6 - 7)',
				'Trips' => 'Trips',
				'' => '',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_60bf719e2d940',
			'label' => 'Top Navigation Menu',
			'name' => 'top_navigation_menu',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'About Us' => 'About Us',
				'Adult Learning' => 'Adult Learning',
				'Adult Learning (Top Buttons)' => 'Adult Learning (Top Buttons)',
				'Adult Learning Main Nav' => 'Adult Learning Main Nav',
				'Alumni' => 'Alumni',
				'Careers Education, Information, Advice and Guidance' => 'Careers Education, Information, Advice and Guidance',
				'Clubs and Activities' => 'Clubs and Activities',
				'Community' => 'Community',
				'Curriculum' => 'Curriculum',
				'Curriculum Rationale' => 'Curriculum Rationale',
				'Ethos and Values' => 'Ethos and Values',
				'Homework' => 'Homework',
				'Houses' => 'Houses',
				'Information' => 'Information',
				'Join Us' => 'Join Us',
				'Letters Home' => 'Letters Home',
				'Main Menu' => 'Main Menu',
				'Parents' => 'Parents',
				'Picture Gallery' => 'Picture Gallery',
				'Pupils' => 'Pupils',
				'Staff' => 'Staff',
				'Subjects' => 'Subjects',
				'Top Buttons (Top Buttons)' => 'Top Buttons (Top Buttons)',
				'Transition (Year 6 - 7)' => 'Transition (Year 6 - 7)',
				'Trips' => 'Trips',
				'' => '',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_60d9a784cec74',
			'label' => 'Adult Learning Contact',
			'name' => 'adult_learning_contact',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_60d9a7d7cec75',
					'label' => 'Contact Name',
					'name' => 'contact_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60d9a7e3cec76',
					'label' => 'Position',
					'name' => 'position',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60d9a7ebcec77',
					'label' => 'Email Address',
					'name' => 'email_address',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60d9a7f5cec78',
					'label' => 'Telephone Number',
					'name' => 'telephone_number',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_60f7eca0db41c',
			'label' => 'Footer Options',
			'name' => 'footer_options',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_60f7f6ed9bedf',
					'label' => 'Column 1 Title',
					'name' => 'column_1_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60f7f211db41d',
					'label' => 'Column 1 Content',
					'name' => 'col1_content',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => 370,
					'rows' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_60f7f226db41e',
					'label' => 'Social Media',
					'name' => 'social_media',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => '',
					'sub_fields' => array(
						array(
							'key' => 'field_60f7f27adb41f',
							'label' => 'platform',
							'name' => 'platform',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'facebook' => 'Facebook',
								'twitter' => 'Twitter',
								'instagram' => 'Instagram',
							),
							'default_value' => false,
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_60f7f29cdb420',
							'label' => 'Platform url',
							'name' => 'platform_url',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_6141d0a8e5435',
							'label' => 'Username',
							'name' => 'username',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array(
					'key' => 'field_60f7ffb4ef4ca',
					'label' => 'Column 2 Title',
					'name' => 'column_2_header',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60f7fb997459a',
					'label' => 'Telephone Number',
					'name' => 'telephone',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60f7fbbb7459b',
					'label' => 'Email Address',
					'name' => 'email_address',
					'type' => 'email',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_60f7fbc97459c',
					'label' => 'Address',
					'name' => 'address',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_60f804d7f8b86',
							'label' => 'Address Line 1',
							'name' => 'address_line_1',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_60f804dff8b87',
							'label' => 'Street',
							'name' => 'street',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_60f804e4f8b88',
							'label' => 'Town',
							'name' => 'town',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_60f804e9f8b89',
							'label' => 'City',
							'name' => 'city',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_60f804eef8b8a',
							'label' => 'County',
							'name' => 'county',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_60f804f3f8b8b',
							'label' => 'Postal Code',
							'name' => 'postal_code',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array(
					'key' => 'field_60f808685e752',
					'label' => 'Column 3 Title',
					'name' => 'column_3_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60f8087c5e753',
					'label' => 'Map Longatude',
					'name' => 'longatude',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60f809205e754',
					'label' => 'Map Latitude',
					'name' => 'latitude',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_60f80dc42e599',
			'label' => 'Sports Centre Options',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_60f80d0efb949',
						'operator' => '==',
						'value' => 'Activate',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_60f80e43807d4',
			'label' => 'Sports Centre Homepage',
			'name' => 'sports_homepage',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => '',
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array(
			'key' => 'field_60f80e6d807d5',
			'label' => 'Logo and Icons',
			'name' => 'sports_logo_and_icons',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_60f80e6d807d6',
					'label' => 'Sports Centre Logo',
					'name' => 'sports_logo',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_60f80e6d807d7',
					'label' => 'Sports Centre Icon',
					'name' => 'sports_icon',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array(
			'key' => 'field_612fa50b743c2',
			'label' => 'Footer Background Image',
			'name' => 'sports_footer_background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_60f80ec5807d8',
			'label' => 'Colours',
			'name' => 'sports_colours',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_60f80ec6807d9',
					'label' => 'Primary Colour',
					'name' => 'primary_colour',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
					'enable_opacity' => 0,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_60f80ec6807da',
					'label' => 'Second Colour',
					'name' => 'second_colour',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#FFFFFF',
					'enable_opacity' => 0,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_60f80ec6807dc',
					'label' => 'Image Border Colour',
					'name' => 'border_colour',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#FFFFFF',
					'enable_opacity' => 0,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_60f80ec6807dd',
					'label' => 'Footer Title Colour',
					'name' => 'footer_title_colour',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'$sportprimarycolour' => 'Primary',
						'$sportsecondarycolour' => 'Secondary',
						'#FFFFFF' => 'White',
					),
					'default_value' => '#FFFFFF',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_60f80ec6807de',
					'label' => 'Footer Icon Colour',
					'name' => 'footer_icon_colour',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'$sportprimarycolour' => 'Primary',
						'$sportsecondarycolour' => 'Secondary',
						'#FFFFFF' => 'White',
					),
					'default_value' => '#FFFFFF',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_60f82819550c4',
					'label' => 'Footer Background Colour',
					'name' => 'footer_background_colour',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 0,
					'return_format' => 'string',
				),
			),
		),
		array(
			'key' => 'field_60f80f529fcaf',
			'label' => 'Fonts',
			'name' => 'sports_fonts',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_60f80f529fcb0',
					'label' => 'Heading Font',
					'name' => 'heading_font',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '16.6',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'\'Raleway\', sans-serif' => 'Raleway',
						'\'Open Sans\', sans-serif' => 'Open Sans',
						'\'Roboto\', sans-serif' => 'Roboto',
						'\'Roboto Slab\', sans-serif' => 'Roboto Slab',
						'\'Josefin Sans\', sans-serif' => 'Josefin Sans',
						'\'Lato\', sans-serif' => 'Lato',
						'\'Libre Franklin \', sans-serif' => 'Libre Franklin',
						'\'Montserrat \', sans-serif' => 'Montserrat',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 1,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_60f80f529fcb1',
					'label' => 'Heading Font weight',
					'name' => 'heading_font_weight',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '16.6',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						300 => 'light-weight',
						400 => 'normal-weight',
						600 => 'bold-weight',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_60f80f529fcb2',
					'label' => 'Body Font',
					'name' => 'body_font',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '16.6',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'\'Raleway\', sans-serif' => 'Raleway',
						'\'Open Sans\', sans-serif' => 'Open Sans',
						'\'Roboto\', sans-serif' => 'Roboto',
						'\'Josefin Sans\', sans-serif' => 'Josefin Sans',
						'\'Lato\', sans-serif' => 'Lato',
						'\'Libre Franklin \', sans-serif' => 'Libre Franklin',
						'\'Montserrat \', sans-serif' => 'Montserrat',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 1,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_60f80f529fcb3',
					'label' => 'Body Font Weight',
					'name' => 'body_font_weight',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '16.6',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						300 => 'light-weight',
						400 => 'normal-weight',
						600 => 'bold-weight',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_60f80f529fcb4',
					'label' => 'Font Previews',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'message' => '<div class="font_choices">
<h3>Raleway</h3>
<p class="raleway">The quick brown fox jumps over the lazy dog</p>
<h3>Roboto</h3>
<p class="roboto">The quick brown fox jumps over the lazy dog</p>
<h3>Roboto Slab</h3>
<p class="robotoslab">The quick brown fox jumps over the lazy dog</p>
<h3>Rubik</h3>
<p class="rubik">The quick brown fox jumps over the lazy dog</p>
<h3>Josefin Sans</h3>
<p class="josefinsans">The quick brown fox jumps over the lazy dog</p>
<h3>Lato</h3>
<p class="lato">The quick brown fox jumps over the lazy dog</p>
<h3>Libre Franklin</h3>
<p class="librefranklin">The quick brown fox jumps over the lazy dog</p>
<h3>Montserrat</h3>
<p class="montserrat">The quick brown fox jumps over the lazy dog</p>
<h3>Open Sans</h3>
<p class="opensans">The quick brown fox jumps over the lazy dog</p>
</div>',
					'new_lines' => '',
					'esc_html' => 0,
				),
			),
		),
		array(
			'key' => 'field_60f813319fcb5',
			'label' => 'Grey Tabs Menu',
			'name' => 'sports_grey_tabs_menu',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'About Us' => 'About Us',
				'Adult Learning' => 'Adult Learning',
				'Adult Learning (Top Buttons)' => 'Adult Learning (Top Buttons)',
				'Adult Learning Main Nav' => 'Adult Learning Main Nav',
				'Alumni' => 'Alumni',
				'Careers Education, Information, Advice and Guidance' => 'Careers Education, Information, Advice and Guidance',
				'Clubs and Activities' => 'Clubs and Activities',
				'Community' => 'Community',
				'Curriculum' => 'Curriculum',
				'Curriculum Rationale' => 'Curriculum Rationale',
				'Ethos and Values' => 'Ethos and Values',
				'Homework' => 'Homework',
				'Houses' => 'Houses',
				'Information' => 'Information',
				'Join Us' => 'Join Us',
				'Letters Home' => 'Letters Home',
				'Main Menu' => 'Main Menu',
				'Parents' => 'Parents',
				'Picture Gallery' => 'Picture Gallery',
				'Pupils' => 'Pupils',
				'Staff' => 'Staff',
				'Subjects' => 'Subjects',
				'Top Buttons (Top Buttons)' => 'Top Buttons (Top Buttons)',
				'Transition (Year 6 - 7)' => 'Transition (Year 6 - 7)',
				'Trips' => 'Trips',
				'' => '',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_60f816479fcb6',
			'label' => 'Top Navigation Menu',
			'name' => 'sports_top_navigation_menu',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'About Us' => 'About Us',
				'Adult Learning' => 'Adult Learning',
				'Adult Learning (Top Buttons)' => 'Adult Learning (Top Buttons)',
				'Adult Learning Main Nav' => 'Adult Learning Main Nav',
				'Alumni' => 'Alumni',
				'Careers Education, Information, Advice and Guidance' => 'Careers Education, Information, Advice and Guidance',
				'Clubs and Activities' => 'Clubs and Activities',
				'Community' => 'Community',
				'Curriculum' => 'Curriculum',
				'Curriculum Rationale' => 'Curriculum Rationale',
				'Ethos and Values' => 'Ethos and Values',
				'Homework' => 'Homework',
				'Houses' => 'Houses',
				'Information' => 'Information',
				'Join Us' => 'Join Us',
				'Letters Home' => 'Letters Home',
				'Main Menu' => 'Main Menu',
				'Parents' => 'Parents',
				'Picture Gallery' => 'Picture Gallery',
				'Pupils' => 'Pupils',
				'Staff' => 'Staff',
				'Subjects' => 'Subjects',
				'Top Buttons (Top Buttons)' => 'Top Buttons (Top Buttons)',
				'Transition (Year 6 - 7)' => 'Transition (Year 6 - 7)',
				'Trips' => 'Trips',
				'' => '',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_60f816619fcb7',
			'label' => 'Sports Centre Contact',
			'name' => 'sports_contact',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_60f816619fcb8',
					'label' => 'Contact Name',
					'name' => 'contact_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60f816619fcb9',
					'label' => 'Position',
					'name' => 'position',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60f816619fcba',
					'label' => 'Email Address',
					'name' => 'email_address',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60f816619fcbb',
					'label' => 'Telephone Number',
					'name' => 'telephone_number',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_60f8168d9fcbc',
			'label' => 'Footer Options',
			'name' => 'sports_footer_options',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_60f8168d9fcbd',
					'label' => 'Column 1 Title',
					'name' => 'column_1_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60f8168d9fcbe',
					'label' => 'Column 1 Content',
					'name' => 'col1_content',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => 370,
					'rows' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_60f8168d9fcbf',
					'label' => 'Social Media',
					'name' => 'social_media',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => '',
					'sub_fields' => array(
						array(
							'key' => 'field_60f8168d9fcc0',
							'label' => 'platform',
							'name' => 'platform',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'facebook' => 'Facebook',
								'twitter' => 'Twitter',
								'instagram' => 'Instagram',
							),
							'default_value' => false,
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_60f8168d9fcc1',
							'label' => 'Platform url',
							'name' => 'platform_url',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_6141d0d1e5436',
							'label' => 'Username',
							'name' => 'username',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array(
					'key' => 'field_60f8168d9fcc2',
					'label' => 'Column 2 Title',
					'name' => 'column_2_header',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60f8168d9fcc3',
					'label' => 'Telephone Number',
					'name' => 'telephone',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60f8168d9fcc4',
					'label' => 'Email Address',
					'name' => 'email_address',
					'type' => 'email',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_60f8168d9fcc5',
					'label' => 'Address',
					'name' => 'address',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_60f8168d9fcc6',
							'label' => 'Address Line 1',
							'name' => 'address_line_1',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_60f8168d9fcc7',
							'label' => 'Street',
							'name' => 'street',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_60f8168d9fcc8',
							'label' => 'Town',
							'name' => 'town',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_60f8168d9fcc9',
							'label' => 'City',
							'name' => 'city',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_60f8168d9fcca',
							'label' => 'County',
							'name' => 'county',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_60f8168d9fccb',
							'label' => 'Postal Code',
							'name' => 'postal_code',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array(
					'key' => 'field_60f8168d9fccc',
					'label' => 'Column 3 Title',
					'name' => 'column_3_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60f8168d9fccd',
					'label' => 'Map Longatude',
					'name' => 'longatude',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60f8168d9fcce',
					'label' => 'Map Latitude',
					'name' => 'latitude',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_60faef9d846b7',
			'label' => 'Cookie Notice',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_60faefab846b8',
			'label' => 'Cookie Notice Message',
			'name' => 'cookie_notice_message',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'This site uses cookies to enhance user experience.',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_60faefb6846b9',
			'label' => 'Cookie Policy Page',
			'name' => 'cookie_policy_page',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'page',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'school-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));
